# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8"
        dotnet-quality: preview

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Build
      run: dotnet publish

    - name: Extract App Version
      id: extract-version
      run: $version = (Select-Xml -Path Servel.NET\Servel.NET.csproj -XPath '//Version[1]/text()[1]').Node.InnerText; "APP_VERSION=$version" >> "$GITHUB_OUTPUT"; cat "$GITHUB_OUTPUT"

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: Servel.NET\bin\x64\Release\win-x64\publish

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: v${{ steps.extract-version.outputs.APP_VERSION }}
        #tag_name: v${{ env.APP_VERSION }}
        files: |
          Servel.NET\bin\x64\Release\win-x64\publish\*
